services:
  preprocessing:
    image: chand1012/tensorflow:2.5.0
    volumes:
      - /Users/erickkbentz/workplace/docker-ml-learning/ml-pipeline/data:/data
      - /Users/erickkbentz/workplace/docker-ml-learning/ml-pipeline/src:/opt/ml/code
    working_dir: /opt/ml/code
    entrypoint: /bin/bash
    command: -c 'pip install --no-cache-dir -r /opt/ml/code/requirements.txt && python preprocessing/process.py --output_path /data --fraction 0.5'
  training:
    image: chand1012/tensorflow:2.5.0
    volumes:
      - /Users/erickkbentz/workplace/docker-ml-learning/ml-pipeline/output:/output
      - /Users/erickkbentz/workplace/docker-ml-learning/ml-pipeline/data:/data
      - /Users/erickkbentz/workplace/docker-ml-learning/ml-pipeline/src:/opt/ml/code
    working_dir: /opt/ml/code
    entrypoint: /bin/bash
    command: -c 'pip install --no-cache-dir -r /opt/ml/code/requirements.txt && python training/train.py --input_path /data/training_data.npz --output_path /output'
    depends_on:
      preprocessing:
        condition: service_completed_successfully
  serving:
    image: chand1012/tensorflow:2.5.0
    ports:
      - 8080:8080
    volumes:
      - /Users/erickkbentz/workplace/docker-ml-learning/ml-pipeline/output:/output
      - /Users/erickkbentz/workplace/docker-ml-learning/ml-pipeline/src:/opt/ml/code
    working_dir: /opt/ml/code
    entrypoint: /bin/bash
    command: -c 'pip install --no-cache-dir -r /opt/ml/code/requirements.txt && python serving/serve.py --model_path /output/cnn_model.h5'
    depends_on:
      training:
        condition: service_completed_successfully